function [femregion]=create_dof_new(Dati,region)

ne     = region.ne;
nedge  = region.nedges;
degree = Dati.fem;
id     = region.id;
tag    = region.tag;

nln=0.5.*(degree+1).*(degree+2);


femregion=struct('fem',Dati.fem,...
    'nedges', nedge,...
    'nln',nln,...
    'ne',ne,...
    'ndof_a',nln*(size(find(region.tag=='A'),1)),...
    'ne_a',(size(find(region.tag=='A'),1)),...
    'nqn',Dati.nqn,...
    'coord',region.coord,...
    'BBox',region.BBox,...
    'id',id);

%     'ndof_e',nln*(size(find(region.tag=='E'),1)),...
    
%     'ndof_p',nln*(size(find(region.tag=='P'),1)),...
%     'ne_e',(size(find(region.tag=='E'),1)),...
    
%     'ne_p',(size(find(region.tag=='P'),1)),...


%'ndof',nln*ne,...
    
femregion.coords_element = region.coords_element;
femregion.connectivity = region.connectivity;
femregion.area = region.area;
femregion.max_kb = region.max_kb;
femregion.tag = region.tag;
